name: First Challenge

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: "Format Image Docker - image:tag"
        required: false
        type: string
        default: "alpine:latest"

jobs:
  desafio:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Docker Image
        shell: bash
        run: |
          IMAGE="${{ inputs.docker_image }}"
      
      - name: Download Docker Image
        run: |
          docker pull "${{ inputs.docker_image }}"
      
      - name: List Docker Image
        run: |
          docker images
      
      # plus challenge
      # - name: Docker Scout vulnerability scan
      #   uses: docker/scout-action@v1
      #   with:
      #     command: cves
      #     image: "${{ inputs.docker_image }}"
